-- SPDX-FileCopyrightText: 2026 TinyPhi
-- SPDX-License-Identifier: AGPL-3.0-only
-- Generated by scripts/check-schema-snapshot.sh update (make schema-snapshot). Do not edit.

CREATE SCHEMA platform;

ALTER SCHEMA platform OWNER TO assetflow_migrator;

CREATE FUNCTION platform.resolve_organization(p_idp_organization_id text) RETURNS TABLE(id uuid, status text)
    LANGUAGE sql STABLE SECURITY DEFINER
    SET search_path TO 'pg_catalog', 'pg_temp'
    AS $$
    SELECT o.id, o.status
    FROM public.organizations AS o
    WHERE o.idp_organization_id = p_idp_organization_id
$$;

ALTER FUNCTION platform.resolve_organization(p_idp_organization_id text) OWNER TO assetflow_resolver;

CREATE TABLE public.organizations (
    id uuid NOT NULL,
    slug text NOT NULL,
    name text NOT NULL,
    idp_organization_id text NOT NULL,
    domain_key text NOT NULL,
    settings jsonb DEFAULT '{}'::jsonb NOT NULL,
    status text DEFAULT 'active'::text NOT NULL,
    version integer DEFAULT 1 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT organizations_settings_object_check CHECK ((jsonb_typeof(settings) = 'object'::text)),
    CONSTRAINT organizations_status_check CHECK ((status = ANY (ARRAY['active'::text, 'suspended'::text, 'archived'::text]))),
    CONSTRAINT organizations_version_check CHECK ((version >= 1))
);

ALTER TABLE ONLY public.organizations FORCE ROW LEVEL SECURITY;

ALTER TABLE public.organizations OWNER TO assetflow_migrator;

ALTER TABLE ONLY public.organizations
    ADD CONSTRAINT organizations_idp_organization_id_key UNIQUE (idp_organization_id);

ALTER TABLE ONLY public.organizations
    ADD CONSTRAINT organizations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.organizations
    ADD CONSTRAINT organizations_slug_key UNIQUE (slug);

ALTER TABLE public.organizations ENABLE ROW LEVEL SECURITY;

CREATE POLICY organizations_delete ON public.organizations FOR DELETE USING ((id = (NULLIF(current_setting('app.organization_id'::text, true), ''::text))::uuid));

CREATE POLICY organizations_insert ON public.organizations FOR INSERT WITH CHECK ((id = (NULLIF(current_setting('app.organization_id'::text, true), ''::text))::uuid));

CREATE POLICY organizations_resolver_select ON public.organizations FOR SELECT TO assetflow_resolver USING (true);

CREATE POLICY organizations_select ON public.organizations FOR SELECT USING ((id = (NULLIF(current_setting('app.organization_id'::text, true), ''::text))::uuid));

CREATE POLICY organizations_update ON public.organizations FOR UPDATE USING ((id = (NULLIF(current_setting('app.organization_id'::text, true), ''::text))::uuid)) WITH CHECK ((id = (NULLIF(current_setting('app.organization_id'::text, true), ''::text))::uuid));

GRANT USAGE ON SCHEMA platform TO assetflow_api;

GRANT ALL ON SCHEMA public TO assetflow_migrator;
GRANT USAGE ON SCHEMA public TO assetflow_api;
GRANT USAGE ON SCHEMA public TO assetflow_worker;
GRANT USAGE ON SCHEMA public TO assetflow_readonly;
GRANT USAGE ON SCHEMA public TO assetflow_resolver;

REVOKE ALL ON FUNCTION platform.resolve_organization(p_idp_organization_id text) FROM PUBLIC;
GRANT ALL ON FUNCTION platform.resolve_organization(p_idp_organization_id text) TO assetflow_api;

GRANT SELECT ON TABLE public.organizations TO assetflow_api;

GRANT SELECT(id) ON TABLE public.organizations TO assetflow_resolver;

GRANT SELECT(idp_organization_id) ON TABLE public.organizations TO assetflow_resolver;

GRANT SELECT(status) ON TABLE public.organizations TO assetflow_resolver;

