#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 TinyPhi
# SPDX-License-Identifier: AGPL-3.0-only
#
# Migration round trip and schema drift check (master plan §C9.3 "migrations" job).
#
#   check-schema-snapshot.sh check    upgrade head -> downgrade -1 -> upgrade head, then compare
#                                     pg_dump --schema-only with backend/migrations/schema.snapshot.sql
#   check-schema-snapshot.sh update   upgrade head, then rewrite the snapshot (commit the result)
#
# Needs an EMPTY PostgreSQL 16 database in ASSETFLOW_MIGRATION_DATABASE_URL (a CREATEROLE account,
# because migration 0000_roles creates the group roles); ASSETFLOW_DATABASE_URL is used when it is
# unset (CI's service container). pg_dump must be a PostgreSQL 16 client; PG_DUMP overrides the
# command (e.g. PG_DUMP="docker exec <container> pg_dump" with a URL valid inside that container).
#
# The dump is normalized so it only changes when the schema does: comment lines, SET lines, the
# per-run \restrict key and the alembic_version table (owned by whoever ran the migration) are
# removed, and runs of blank lines are squeezed. Owners, grants and policies are kept on purpose.
set -euo pipefail

mode="${1:-check}"
UV="${UV:-uv}"
PG_DUMP="${PG_DUMP:-pg_dump}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SNAPSHOT="${ROOT}/backend/migrations/schema.snapshot.sql"

export ASSETFLOW_MIGRATION_DATABASE_URL="${ASSETFLOW_MIGRATION_DATABASE_URL:-${ASSETFLOW_DATABASE_URL:-}}"
if [ -z "${ASSETFLOW_MIGRATION_DATABASE_URL}" ]; then
  echo "check-schema-snapshot: set ASSETFLOW_MIGRATION_DATABASE_URL (or ASSETFLOW_DATABASE_URL) to an empty PostgreSQL 16 database." >&2
  exit 1
fi
# PG_DUMP may be a multi-word command on purpose (see the header); its first word must exist.
if ! command -v "${PG_DUMP%% *}" >/dev/null 2>&1; then
  echo "check-schema-snapshot: '${PG_DUMP%% *}' not found; install the PostgreSQL 16 client or set PG_DUMP." >&2
  exit 1
fi

normalize() {
  grep -Ev '^(--|SET |SELECT pg_catalog\.set_config|\\(un)?restrict )' | cat -s
}

dump() {
  # shellcheck disable=SC2086
  ${PG_DUMP} --schema-only --exclude-table=public.alembic_version "${PG_DUMP_URL:-${ASSETFLOW_MIGRATION_DATABASE_URL}}" | normalize
}

cd "${ROOT}/backend"
case "${mode}" in
  check)
    "${UV}" run alembic upgrade head
    "${UV}" run alembic downgrade -1
    "${UV}" run alembic upgrade head
    actual="$(mktemp)"
    trap 'rm -f "${actual}"' EXIT
    dump >"${actual}"
    if ! diff -u <(normalize <"${SNAPSHOT}") "${actual}"; then
      echo "check-schema-snapshot: the migrated schema differs from backend/migrations/schema.snapshot.sql (diff above)." >&2
      echo "If the change is intended, run 'make schema-snapshot' against an empty database and commit the file." >&2
      exit 1
    fi
    echo "check-schema-snapshot: upgrade/downgrade/upgrade passed and the schema matches the snapshot."
    ;;
  update)
    "${UV}" run alembic upgrade head
    # REUSE-IgnoreStart
    {
      echo "-- SPDX-FileCopyrightText: 2026 TinyPhi"
      echo "-- SPDX-License-Identifier: AGPL-3.0-only"
      echo "-- Generated by scripts/check-schema-snapshot.sh update (make schema-snapshot). Do not edit."
      dump
    } >"${SNAPSHOT}"
    # REUSE-IgnoreEnd
    echo "check-schema-snapshot: wrote backend/migrations/schema.snapshot.sql."
    ;;
  *)
    echo "usage: check-schema-snapshot.sh check|update" >&2
    exit 2
    ;;
esac
