#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 TinyPhi
# SPDX-License-Identifier: AGPL-3.0-only
"""Generate docs/reference/error-codes.md from the error registry in backend/app/core/problems.py.

Every AssetFlow error code gets an entry with an explicit anchor equal to the code, which is what the
``type`` URI of a problem response points at (§C1.5.1).

Usage (from the repository root or backend/):
    uv run --project backend python scripts/gen-error-codes.py           write the file
    uv run --project backend python scripts/gen-error-codes.py --check   exit 1 if the file is stale
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
BACKEND_DIR = REPO_ROOT / "backend"
OUTPUT = REPO_ROOT / "docs" / "reference" / "error-codes.md"

if str(BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(BACKEND_DIR))

from app.core.problems import ERROR_REGISTRY, problem_type_url

HEADER = """<!--
SPDX-FileCopyrightText: 2026 TinyPhi
SPDX-License-Identifier: AGPL-3.0-only
-->

<!-- Generated by scripts/gen-error-codes.py from backend/app/core/problems.py. Do not edit by hand. -->

# Error codes

Every error response is RFC 9457 Problem Details (`application/problem+json`, §C1.5.1):

| Field | Meaning |
| --- | --- |
| `type` | Link to the code's entry on this page |
| `title` | Short summary; the same for every occurrence of the code |
| `status` | HTTP status |
| `detail` | What happened in this case; never secrets, SQL, stack traces or exception text |
| `instance` | The request path |
| `code` | The AssetFlow error code (`<area>.<reason>`); clients branch on this, not on text |
| `request_id` | Correlates with server logs and traces (also sent as the `X-Request-ID` header) |
| `errors` | Field-level validation errors: `field`, `message` |

## Summary

| Code | Status | Title |
| --- | :---: | --- |
"""


def render() -> str:
    """Return the full Markdown text of the error-code reference."""
    entries = sorted(ERROR_REGISTRY, key=lambda cls: cls.code)
    codes = [cls.code for cls in entries]
    duplicates = sorted({code for code in codes if codes.count(code) > 1})
    if duplicates:
        raise SystemExit(f"duplicate error codes in ERROR_REGISTRY: {', '.join(duplicates)}")

    lines = [HEADER.rstrip("\n")]
    lines.extend(f"| [`{cls.code}`](#{cls.code}) | {cls.status_code} | {cls.title} |" for cls in entries)
    lines.extend(["", "## Codes", ""])
    for cls in entries:
        lines.extend(
            [
                f'<a id="{cls.code}"></a>',
                "",
                f"### `{cls.code}`",
                "",
                f"- **Status:** {cls.status_code}",
                f"- **Title:** {cls.title}",
                f"- **Default detail:** {cls.default_detail}",
                f"- **Error class:** `{cls.__name__}`",
                f"- **Type URI:** `{problem_type_url(cls.code)}`",
                "",
                cls.description,
                "",
            ]
        )
    return "\n".join(lines).rstrip("\n") + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0] if __doc__ else None)
    parser.add_argument("--check", action="store_true", help="fail if the file is not up to date")
    args = parser.parse_args(argv)
    text = render()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != text:
            sys.stderr.write(f"{OUTPUT.relative_to(REPO_ROOT)} is stale; run scripts/gen-error-codes.py\n")
            return 1
        return 0
    OUTPUT.write_text(text, encoding="utf-8", newline="\n")
    sys.stdout.write(f"wrote {OUTPUT.relative_to(REPO_ROOT)}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
