# SPDX-FileCopyrightText: 2026 TinyPhi
# SPDX-License-Identifier: AGPL-3.0-only
"""RFC 9457 Problem Details: error classes, the error-code registry and exception handlers (§C1.5.1, §C4.5).

Every error response is ``application/problem+json`` with ``type``, ``title``, ``status``, ``detail``,
``instance`` and the AssetFlow extensions ``code``, ``request_id`` and ``errors``. ``type`` links to
the code's entry in ``docs/reference/error-codes.md`` (generated by ``scripts/gen-error-codes.py``).
Codes are ``<area>.<reason>`` in lowercase snake case. ``detail`` never carries secrets, SQL, stack
traces or exception text: unexpected exceptions are logged server-side and answered generically.
"""

from __future__ import annotations

import logging
from collections.abc import Mapping
from http import HTTPStatus
from typing import Any, ClassVar

from fastapi import Request
from fastapi.exceptions import RequestValidationError
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field
from starlette.exceptions import HTTPException as StarletteHTTPException

__all__ = [
    "ERROR_CODES_DOC_URL",
    "ERROR_REGISTRY",
    "ConflictError",
    "HttpError",
    "InternalError",
    "MethodNotAllowedError",
    "NotFoundError",
    "PermissionDeniedError",
    "ProblemDetail",
    "ProblemError",
    "RateLimitedError",
    "RouteNotFoundError",
    "SecretsUnavailableError",
    "ServiceUnavailableError",
    "UnauthorizedError",
    "ValidationFailedError",
    "http_exception_handler",
    "problem_error_handler",
    "problem_response",
    "problem_type_url",
    "request_validation_handler",
    "unhandled_exception_handler",
]

ERROR_CODES_DOC_URL = "https://github.com/tinyphi/assetflow/blob/main/docs/reference/error-codes.md"

_log = logging.getLogger("assetflow.http")


def problem_type_url(code: str) -> str:
    """Return the ``type`` URI of an error code: its anchor in docs/reference/error-codes.md."""
    return f"{ERROR_CODES_DOC_URL}#{code}"


class FieldError(BaseModel):
    """One field-level entry of the ``errors`` extension."""

    field: str = Field(description="Dotted location of the offending field, e.g. body.name")
    message: str = Field(description="What is wrong with the field")


class ProblemDetail(BaseModel):
    """RFC 9457 Problem Details body with the AssetFlow extensions."""

    type: str = Field(description="Link to the code's entry in docs/reference/error-codes.md")
    title: str = Field(description="Short summary; the same for every occurrence of the code")
    status: int = Field(description="HTTP status code")
    detail: str = Field(description="What happened in this case; never secrets, SQL or stack traces")
    instance: str | None = Field(default=None, description="The request path")
    code: str = Field(description="AssetFlow error code (<area>.<reason>)")
    request_id: str | None = Field(default=None, description="Correlates with logs and traces")
    errors: list[FieldError] | None = Field(default=None, description="Field-level validation errors")


class ProblemError(Exception):
    """Base of every AssetFlow error that maps to a problem response.

    Subclasses set ``status_code``, ``code``, ``title``, ``default_detail`` and ``description``
    (the last one feeds the generated error-code reference).
    """

    status_code: ClassVar[int] = 500
    code: ClassVar[str] = "internal.error"
    title: ClassVar[str] = "Internal server error"
    default_detail: ClassVar[str] = "An unexpected error occurred. Quote the request id when reporting it."
    description: ClassVar[str] = "Base class; not raised directly."

    def __init__(
        self,
        detail: str | None = None,
        *,
        errors: list[FieldError] | None = None,
        headers: Mapping[str, str] | None = None,
    ) -> None:
        self.detail = detail or self.default_detail
        self.errors = errors
        self.headers = dict(headers) if headers else None
        super().__init__(self.detail)


class InternalError(ProblemError):
    status_code = 500
    code = "internal.error"
    title = "Internal server error"
    default_detail = "An unexpected error occurred. Quote the request id when reporting it."
    description = "An unexpected server-side failure. Details are only in the server logs, by request id."


class ValidationFailedError(ProblemError):
    status_code = 422
    code = "validation.invalid_field"
    title = "Validation failed"
    default_detail = "One or more fields are invalid. See errors for each field."
    description = "The request body, path or query failed validation. `errors` lists each field."


class UnauthorizedError(ProblemError):
    status_code = 401
    code = "auth.unauthorized"
    title = "Authentication required"
    default_detail = "Sign in to use this endpoint."
    description = "No valid session or token was presented."

    def __init__(self, detail: str | None = None, *, errors: list[FieldError] | None = None) -> None:
        super().__init__(detail, errors=errors, headers={"WWW-Authenticate": "Bearer"})


class PermissionDeniedError(ProblemError):
    status_code = 403
    code = "auth.permission_denied"
    title = "Permission denied"
    default_detail = "You do not have permission for this action."
    description = "The caller is signed in but lacks the required permission."


class NotFoundError(ProblemError):
    status_code = 404
    code = "resource.not_found"
    title = "Resource not found"
    default_detail = "The requested resource does not exist."
    description = "Generic not-found; modules raise `<entity>.not_found` subclasses instead where possible."


class RouteNotFoundError(ProblemError):
    status_code = 404
    code = "http.not_found"
    title = "Route not found"
    default_detail = "No endpoint exists at this path."
    description = "The request path does not match any API endpoint."


class MethodNotAllowedError(ProblemError):
    status_code = 405
    code = "http.method_not_allowed"
    title = "Method not allowed"
    default_detail = "This endpoint does not support the request method."
    description = "The path exists but not for this HTTP method."


class ConflictError(ProblemError):
    status_code = 409
    code = "resource.conflict"
    title = "Resource conflict"
    default_detail = "The request conflicts with the current state of the resource."
    description = "Generic conflict; modules raise `<entity>.version_conflict` subclasses where possible."


class RateLimitedError(ProblemError):
    status_code = 429
    code = "rate_limit.exceeded"
    title = "Too many requests"
    default_detail = "Too many requests. Retry later."
    description = "A rate limit was exceeded; the response carries `Retry-After`."

    def __init__(self, detail: str | None = None, *, retry_after_seconds: int = 60) -> None:
        super().__init__(detail, headers={"Retry-After": str(retry_after_seconds)})


class HttpError(ProblemError):
    status_code = 400
    code = "http.error"
    title = "Request could not be processed"
    default_detail = "The request could not be processed."
    description = "Any other HTTP-level error raised by the framework; `status` carries the HTTP status."


class ServiceUnavailableError(ProblemError):
    status_code = 503
    code = "platform.unavailable"
    title = "Service unavailable"
    default_detail = "The service is not ready. Retry later."
    description = "A platform dependency (database, provider) is not ready."


class SecretsUnavailableError(ProblemError):
    status_code = 503
    code = "platform.secrets_unavailable"
    title = "Secrets provider unavailable"
    default_detail = "A required secret could not be read. Retry later."
    description = (
        "The secrets provider is sealed, unreachable or does not hold a required secret. "
        "The detail never contains the secret value."
    )


ERROR_REGISTRY: tuple[type[ProblemError], ...] = (
    InternalError,
    ValidationFailedError,
    UnauthorizedError,
    PermissionDeniedError,
    NotFoundError,
    RouteNotFoundError,
    MethodNotAllowedError,
    ConflictError,
    RateLimitedError,
    HttpError,
    ServiceUnavailableError,
    SecretsUnavailableError,
)

_BY_STATUS: dict[int, type[ProblemError]] = {
    401: UnauthorizedError,
    403: PermissionDeniedError,
    404: RouteNotFoundError,
    405: MethodNotAllowedError,
    429: RateLimitedError,
    503: ServiceUnavailableError,
}


def __getattr__(name: str) -> Any:
    """Re-export ``ConfigError`` lazily; it lives in app.core.config (avoids an import cycle)."""
    if name == "ConfigError":
        from app.core.config import ConfigError  # noqa: PLC0415 - deliberate lazy import

        return ConfigError
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def _request_id(request: Request) -> str | None:
    value = getattr(request.state, "request_id", None)
    return value if isinstance(value, str) else None


def problem_response(
    *,
    status: int,
    code: str,
    title: str,
    detail: str,
    instance: str | None = None,
    request_id: str | None = None,
    errors: list[FieldError] | None = None,
    headers: Mapping[str, str] | None = None,
) -> JSONResponse:
    """Build an ``application/problem+json`` response."""
    body = ProblemDetail(
        type=problem_type_url(code),
        title=title,
        status=status,
        detail=detail,
        instance=instance,
        code=code,
        request_id=request_id,
        errors=errors,
    )
    out_headers = dict(headers or {})
    if request_id:
        out_headers["X-Request-ID"] = request_id
    return JSONResponse(
        status_code=status,
        content=body.model_dump(exclude_none=True),
        media_type="application/problem+json",
        headers=out_headers,
    )


def _from_error(request: Request, err: ProblemError, *, status: int | None = None) -> JSONResponse:
    return problem_response(
        status=status or err.status_code,
        code=err.code,
        title=err.title,
        detail=err.detail,
        instance=request.url.path,
        request_id=_request_id(request),
        errors=err.errors,
        headers=err.headers,
    )


async def problem_error_handler(request: Request, exc: Exception) -> JSONResponse:
    """Handle a raised ``ProblemError``."""
    if not isinstance(exc, ProblemError):
        return await unhandled_exception_handler(request, exc)
    return _from_error(request, exc)


async def request_validation_handler(request: Request, exc: Exception) -> JSONResponse:
    """Map FastAPI request validation to ``validation.invalid_field`` with the ``errors`` extension.

    Only the location and message of each error are returned; submitted input values are not echoed.
    """
    if not isinstance(exc, RequestValidationError):
        return await unhandled_exception_handler(request, exc)
    field_errors = [
        FieldError(field=".".join(str(part) for part in err.get("loc", ())), message=str(err.get("msg", "")))
        for err in exc.errors()
    ]
    return _from_error(request, ValidationFailedError(errors=field_errors))


async def http_exception_handler(request: Request, exc: Exception) -> JSONResponse:
    """Map framework ``HTTPException`` (404 route, 405 method, ...) to problem responses.

    The framework's own ``detail`` text is not forwarded; each code has a fixed detail.
    """
    if not isinstance(exc, StarletteHTTPException):
        return await unhandled_exception_handler(request, exc)
    err_cls = _BY_STATUS.get(exc.status_code, HttpError)
    err = err_cls()
    if exc.headers:
        err.headers = {**(err.headers or {}), **exc.headers}
    if err_cls is HttpError:
        try:
            title = HTTPStatus(exc.status_code).phrase
        except ValueError:
            title = HttpError.title
        return problem_response(
            status=exc.status_code,
            code=err.code,
            title=title,
            detail=err.detail,
            instance=request.url.path,
            request_id=_request_id(request),
            headers=err.headers,
        )
    return _from_error(request, err)


async def unhandled_exception_handler(request: Request, exc: Exception) -> JSONResponse:
    """Answer any unexpected exception with ``internal.error``; the details go only to the server log."""
    request_id = _request_id(request)
    _log.error(
        "http.unhandled_exception",
        exc_info=(type(exc), exc, exc.__traceback__),
        extra={"request_id": request_id, "error_code": InternalError.code},
    )
    return _from_error(request, InternalError())
